DELETE FROM users;
ALTER TABLE users ALTER COLUMN user_id RESTART WITH 1;

DELETE FROM items;
ALTER TABLE items ALTER COLUMN item_id RESTART WITH 1;

DELETE FROM comments;
ALTER TABLE comments ALTER COLUMN comment_id RESTART WITH 1;

DELETE FROM requests;
ALTER TABLE requests ALTER COLUMN request_id RESTART WITH 1;

DELETE FROM bookings;
ALTER TABLE bookings ALTER COLUMN booking_id RESTART WITH 1;